### ISSUE TITLE
Documentation doesn't report library is compatible with Android >=Lollipop (5)

### ISSUE THREAD

**Issue by Neogene** [inthepocket/ibeacon-scanner-android#17]
Library is >= 5 but is never reported on documentation, only checking source code, or running on a device with android <5 will report this (crash due to class not def due to @TargetApi(Build.VERSION_CODES.LOLLIPOP)).

**Comment by eliaslecomte** [comment]
That is correct. I've added it to the [wiki](https://github.com/inthepocket/ibeacon-scanner-android/wiki). Intellisense in Android Studio should report this requirement as well.
