### ISSUE TITLE
Bug initializing the ManufacturerDataMask

### ISSUE THREAD

**Issue by dahLucky** [inthepocket/ibeacon-scanner-android#21]
Hi Elias, 
I just created a pull request #20  to fix a bug during the ManufacturerDataMask initialisation. 

Bytes of the DataMask are initialised with 0b00000001 instead of
0b11111111, hence only the least significant bit of the DataMask and the
result data are being compared. Effectively the current FilterMask is just an
even/odd filter for the selected bytes. See [ScanFilter.java in Android Sources](https://android.googlesource.com/platform/frameworks/base/+/d5324e4/core/java/android/bluetooth/le/ScanFilter.java#367)
`if ((dataMask[i] & parsedData[i]) != (dataMask[i] & data[i]))`

**Comment by eliaslecomte** [comment]
Thanks for your PR!
