### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by mansya** [inthepocket/ibeacon-scanner-android#24]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by eliaslecomte** [comment]
Hey,

Sorry I never came back to you. If you are willing to create an icon for us, feel free to make some proposals!

**Comment by mansya** [comment]
can you update the code in this project. because I only contribute to projects that have been updated in the last 5 months
