### ISSUE TITLE
Cannot access 'DefaultScanService': it is public/*package*/ in 'mobi.inthepocket.android.beacons.ibeaconscanner'	

### ISSUE THREAD

**Issue by milkrun** [inthepocket/ibeacon-scanner-android#25]
Trying to use with Kotlin and I'm getting this error

**Comment by shafiullakhan** [comment]
Same error any updates on this?

**Comment by eliaslecomte** [comment]
If you PR a fix, we will for sure merge it in.

**Comment by testdriveit** [comment]
Make DefaultScanService public in declaration. Kotlin does'nt see it.

**Comment by eliaslecomte** [comment]
Will be taken up in 3.0!
