### ISSUE TITLE
Does not work after phone restart

### ISSUE THREAD

**Issue by dima-zemingo** [inthepocket/ibeacon-scanner-android#30]
After restarting the phone, I'm not getting any updates. Tested on Nexus 6P using android 8.1.0 and Galaxy J7 Prime android 7.0

**Comment by eliaslecomte** [comment]
Of course you need to manually start scanning when a smartphone reboots.

You have to listen to the BOOT_COMPLETED broadcast in your AndroidManifest:

`<receiver
            android:name=".broadcastreceivers.BootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>`

And this is an example broadcast receiver class:

`public class BootReceiver extends BroadcastReceiver
{
    @Override
    public void onReceive(final Context context, final Intent intent)
    {
        if (intent.getAction().equals(Manifest.permission.RECEIVE_BOOT_COMPLETED))
        {
            // device rebooted, start service
            ...
        }
    }
}`
